name: FaceMask
version: ${project.version}
main: net.kunmc.lab.facemask.FaceMask
api-version: 1.16
commands:
  facemask:
    usage: |-
      /facemask set <player> <facename>
      /facemask unset <player>
      /facemask get <facename>