name: Kusomaru
version: ${project.version}
main: net.kunmc.lab.kusomaru.Kusomaru
api-version: 1.16
commands:
  kusomaru:
    usage: |-
      /kusomaru set <player> <facename>
      /kusomaru unset <player>